kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: calico
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16" # Calico default
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    networking:
      podSubnet: "192.168.0.0/16"
  - |
    kind: InitConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    skipPhases:
    - addon/kube-proxy
  - |
    kind: JoinConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    skipPhases:
    - addon/kube-proxy
nodes:
  - role: control-plane
  - role: worker
  - role: worker
