kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: calico
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"   # Calico default
nodes:
  - role: control-plane
  - role: worker
  - role: worker